// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AttendantChecks { is_delegado: boolean, is_subdelegado: boolean, is_electo: boolean, is_junta_de_centro: boolean, is_claustro: boolean, is_voluntario: boolean, }