// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttendantChecks } from "./AttendantChecks";
import type { RawAttendant } from "./RawAttendant";

export interface Attendant { raw: RawAttendant, checks: AttendantChecks, }